schema_version: 1

context:
  name: PyCBC
  version: "2.10.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | lower }}-${{ version }}.tar.gz
  sha256: 3c1034e4089d256936c4d80f9c1fa1348c1ff604357a47a4beffbcac2c135edf
  patches:
    # to update the patches for a new release:
    #
    #     # -- checkout the new source release tag
    #     cd /path/to/git/pycbc
    #     git fetch
    #     git checkout <release-tag>
    #     # -- apply the patches on top of the release tag
    #     git am --3way /path/to/git/pycbc-feedstock/recipe/patches/*.patch
    #     <resolve-any-conflicts>
    #     # -- render new patch files
    #     git format-patch <release-tag>
    #     # -- copy them back to the feedstock
    #     cd /path/to/git/pycbc-feedstock
    #     git rm recipe/patches/*.patch
    #     cp /path/to/git/pycbc/*.patch recipe/patches/
    #     git add recipe/patches/*.patch
    #     <update-this-file-as-required>
    # remove lalsuite requirement from python metadata
    - patches/0001-setup.py-remove-lalsuite-install_requires.patch
    # skip regenerating the git_version_info
    # https://github.com/gwastro/pycbc/issues/3917
    - patches/0002-setup.py-don-t-generate-version-info-in-build.patch
    # limit pytest to tests that don't need external data files
    - patches/0003-ignore-tests-that-rely-on-external-data-files.patch

build:
  dynamic_linking:
    overdepending_behavior: error
  number: 1
  script: ${{ PYTHON }} -m pip install . -vv
  skip:
    - win
    # Match upstream Requires-Python
    - match(python, "<3.11")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - if: linux
      then: libgomp
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython >=0.29.21
        - numpy
  host:
    - cython >=0.29.21
    - numpy
    - pip
    - python
    - setuptools
  run:
    - astropy-base >=2.0.3,!=4.2.1,!=4.0.5
    - beautifulsoup4 >=4.6.0
    - cython >=0.29
    - gwdatafind
    - h5py >=3.0.0,!=3.7.0
    - igwn-ligolw
    - igwn-segments
    - jinja2
    - lscsoft-glue >=1.59.3
    - mako >=1.0.1
    - matplotlib-base >=2.0.0
    - mpld3 >=0.3
    - numpy >=1.16.0,!=1.19.0,!=2.2.2
    - pegasus-wms.api >=5.1.1
    - pkg-config
    - pillow
    - pykerr
    - python
    - python-lalframe
    - python-lalsimulation
    - scipy >=0.16.0
    - setuptools
  run_constraints:
    - liblalmetaio !=2.1.0

tests:
  - python:
      imports:
        - pycbc
        - pycbc.bin_utils
        - pycbc.boundaries
        - pycbc.catalog
        - pycbc.conversions
        - pycbc.coordinates
        - pycbc.cosmology
        - pycbc.detector
        - pycbc.distributions
        - pycbc.dq
        - pycbc.events
        - pycbc.fft
        - pycbc.filter
        - pycbc.frame
        - pycbc.inference
        - pycbc.inference.io
        - pycbc.inference.models
        - pycbc.inference.sampler
        - pycbc.inject
        - pycbc.io
        - pycbc.libutils
        - pycbc.noise
        - pycbc.opt
        - pycbc.pnutils
        - pycbc.pool
        - pycbc.population
        - pycbc.psd
        - pycbc.rate
        - pycbc.results
        - pycbc.scheme
        - pycbc.sensitivity
        - pycbc.strain
        - pycbc.tmpltbank
        - pycbc.transforms
        - pycbc.types
        - pycbc.vetoes
        - pycbc.waveform
        - pycbc.workflow
      pip_check: true
  - files:
      source:
        - examples
        - pytest.ini
        - test
    requirements:
      run:
        - dynesty <3.0.0a0
        - epsie
        - fftw
        - ligo-gracedb >=2.10.0
        - mpi4py
        - openssh
        - pytest
        - pytest-xdist
        - if: x86_64
          then: mkl
    script:
      # Skip test_bhspec.py (see https://github.com/gwastro/pycbc/issues/5246)
      - "export PYTEST_ADDOPTS=\"--ignore test/test_bhspec.py\""
      # Skip flaky tests on zen2 (see https://github.com/gwastro/pycbc/issues/5259)
      - "if [[ \"$(conda info)\" == *\"zen2\"* ]]; then export PYTEST_ADDOPTS=\"${PYTEST_ADDOPTS:-} -k 'not test_perfect_match'\"; fi"
      # Skip test_fft_mkl_threaded.py on non-x86_64 platforms
      - if: unix and not x86_64
        then: "export PYTEST_ADDOPTS=\"${PYTEST_ADDOPTS:-} --ignore test/test_fft_mkl_threaded.py\""

      # Run test suite
      - echo "PYTEST_ADDOPTS=${PYTEST_ADDOPTS:-}"
      - python -m pytest test/ -n ${{ env.get("CPU_COUNT", default="1") }}

      # Check that command-line scripts are functional
      # Notes:
      #   - two bash scripts are GNU specific so don't run on macOS
      - "export MPLBACKEND=\"agg\""
      - for prog in ${PREFIX}/bin/pycbc*; do
      - if: osx
        then: >-
          if
          [[ $prog == *"pycbc_copy_output_map" ]]
          || [[ $prog == *"pycbc_stageout_failed_workflow" ]]
          ; then continue; fi
      - $prog --help
      - done

about:
  summary: Core library to analyze gravitational-wave data, find signals, and study their parameters.
  description: |
    PyCBC is a software package used to explore astrophysical sources
    of gravitational waves.
    It contains algorithms that can detect coalescing compact binaries
    and measure the astrophysical parameters of detected sources.
    PyCBC was used in the first direct detection of gravitational
    waves (GW150914) by LIGO and is used in the ongoing analysis of
    LIGO and Virgo data.
  homepage: https://pycbc.org/
  repository: https://github.com/gwastro/pycbc/
  documentation: http://pycbc.org/pycbc/latest/html/
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ahnitz
    - duncanmmacleod
    - maxtrevor
    - spxiwh
    - titodalcanton
