# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HNne+j0gTpFtZUMaqKhpxs+NzptfgLdU8jLTk818APAxTtGWMI9WYMPZ5657rqSYECHq86wjXUIEFaWxucYhJ57KD5OvqjUPguxOjzySmZmx5GbBE45BaWOMWgg+xowOhWhw7ntulhVIGZNxiWpeCft/Alt8toBUa875gbJ4TZYOgPHA5EI1TyqTa1aMhkr/dVcGPrzoUo5fFJAQsLK4Xj3UNwVmLB40QnoupEODlh1tRh7x++7VKa44wuBZfkonSbgJA+wi6bPqsr00QKfAvWaPXusQbOyosUPC0/179EIQPVtVIvyJn4584pmh86Iz+FWPvOD9hd3zRq8awA34lLeQHIJP2n0l0gHunjXBTFAeTvmmwqUfh69/gEw0fzDfeW0nxoaBlDV8y7/IiwEVjXhasaRSG3Kd+SxiWQz3DFjHL9GCBc+nCWDwR4SvF7EnOAw17HENsISAwI5Zum6f96eez0/JJ02HcrTY1lwhqJXyYHhYrzxQsh1hWpaH95C9b0o14cuU1pKjQBXwhRJtLAck8cBF7Ms1X7UqmVYUy4qfgpl1VIMcNS4CrxZglOztgQyJ7y8tZySUBKIMvoxlVfcKyY0QiRSVZKsucf2Kz4BFsBEOIeyL1QzvUZ+ivg1muzLCrqItY0oEuzGexwY00F4Omv3Bx3DCakh55l5VjWw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml