travis:
  secure:
    BINSTAR_TOKEN: HNne+j0gTpFtZUMaqKhpxs+NzptfgLdU8jLTk818APAxTtGWMI9WYMPZ5657rqSYECHq86wjXUIEFaWxucYhJ57KD5OvqjUPguxOjzySmZmx5GbBE45BaWOMWgg+xowOhWhw7ntulhVIGZNxiWpeCft/Alt8toBUa875gbJ4TZYOgPHA5EI1TyqTa1aMhkr/dVcGPrzoUo5fFJAQsLK4Xj3UNwVmLB40QnoupEODlh1tRh7x++7VKa44wuBZfkonSbgJA+wi6bPqsr00QKfAvWaPXusQbOyosUPC0/179EIQPVtVIvyJn4584pmh86Iz+FWPvOD9hd3zRq8awA34lLeQHIJP2n0l0gHunjXBTFAeTvmmwqUfh69/gEw0fzDfeW0nxoaBlDV8y7/IiwEVjXhasaRSG3Kd+SxiWQz3DFjHL9GCBc+nCWDwR4SvF7EnOAw17HENsISAwI5Zum6f96eez0/JJ02HcrTY1lwhqJXyYHhYrzxQsh1hWpaH95C9b0o14cuU1pKjQBXwhRJtLAck8cBF7Ms1X7UqmVYUy4qfgpl1VIMcNS4CrxZglOztgQyJ7y8tZySUBKIMvoxlVfcKyY0QiRSVZKsucf2Kz4BFsBEOIeyL1QzvUZ+ivg1muzLCrqItY0oEuzGexwY00F4Omv3Bx3DCakh55l5VjWw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
